---
name: prometheus-role
description: Роль для установки и настройки Prometheus

# Установка Prometheus
ansible Gauls:
  - name: установить Prometheus
    apt:
      name: prometheus
      state: present
