---
- name: Deploy Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus

- name: Deploy Node Exporter
  hosts: node_exporters
  become: yes
  roles:
    - node_exporter

- name: Deploy ElasticSearch & Kibana
  hosts: elastic
  become: yes
  roles:
    - elastic_kibana

- name: Deploy FluentBit
  hosts: node_exporters
  become: yes
  roles:
    - fluentbit
