all:
  children:
    prometheus:
      hosts:
        prometheus-server:
          ansible_host: <prometheus_ip>
    node_exporters:
      hosts:
        node1:
          ansible_host: <node1_ip>
    elastic:
      hosts:
        elastic-server:
          ansible_host: <elastic_ip>
